### ISSUE TITLE
Accessing directly to dynamic column

### ISSUE THREAD

**Issue by MahdiPishguy** [HalalSoft/laravel-dynamic-column#3]
as we know, we have `json` data format and we can access to this columns with specifying key of array, for example:

```php
//"{"address":"AddressAddress","remember":"0"}"

$options['address']
```

my question is, is it possible to access them with `->` instead of specifying array key? for example:

```php
$options->address
```

**Comment by dyaskur** [comment]
Hi, Sorry for late respond. Update the package to allow you using object. and you need to change 

```
    protected $casts
        = [
            'options' => Dynamic::class,
        ];
```

to
```
    protected $casts
        = [
            'options' => DynamicObject::class,
        ];
```

**Comment by MahdiPishguy** [comment]
@dyaskur Thanks so much :)
